import type { TimelineEvent } from "./musk-career-data"

export const personalEvents: TimelineEvent[] = [
  {
    id: "p1",
    title: "Birth",
    date: new Date("1971-06-28"),
    description:
      "Elon Reeve Musk was born in Pretoria, South Africa, to Maye Musk, a model and dietitian, and Errol Musk, an electromechanical engineer.",
    category: "Personal",
    imageUrl: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "p2",
    title: "Parents' Divorce",
    date: new Date("1979-01-01"),
    description:
      "Elon's parents divorced when he was 8 years old. He chose to live with his father, which he later described as a mistake.",
    category: "Family",
    imageUrl: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "p3",
    title: "First Computer",
    date: new Date("1983-01-01"),
    description:
      "At age 12, Musk bought his first computer and taught himself computer programming. He created a video game called Blastar which he sold for $500.",
    category: "Education",
    imageUrl: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "p4",
    title: "Move to Canada",
    date: new Date("1989-06-01"),
    description:
      "At age 17, Musk moved to Canada to attend Queen's University and to avoid mandatory service in the South African military.",
    category: "Relocation",
    imageUrl: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "p5",
    title: "University of Pennsylvania",
    date: new Date("1992-01-01"),
    description:
      "Musk transferred to the University of Pennsylvania, where he earned a Bachelor of Science degree in Physics and a Bachelor of Science degree in Economics from the Wharton School.",
    category: "Education",
    imageUrl: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "p6",
    title: "Stanford PhD Program",
    date: new Date("1995-01-01"),
    description:
      "Musk was accepted into a PhD program in energy physics/materials science at Stanford University but dropped out after just two days to pursue entrepreneurial aspirations.",
    category: "Education",
    imageUrl: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "p7",
    title: "Marriage to Justine Wilson",
    date: new Date("2000-01-01"),
    description:
      "Musk married his first wife, Canadian author Justine Wilson, whom he met while they were both attending Queen's University.",
    category: "Relationship",
    imageUrl: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "p8",
    title: "First Son",
    date: new Date("2002-05-10"),
    description:
      "Musk's first son, Nevada Alexander Musk, was born but died of sudden infant death syndrome (SIDS) at the age of 10 weeks.",
    category: "Family",
    imageUrl: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "p9",
    title: "Twins Born",
    date: new Date("2004-04-15"),
    description: "Musk and Justine had twin sons, Griffin and Xavier (now Vivian), through in vitro fertilization.",
    category: "Family",
    imageUrl: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "p10",
    title: "Triplets Born",
    date: new Date("2006-01-01"),
    description: "Musk and Justine had triplet sons, Kai, Saxon, and Damian, through in vitro fertilization.",
    category: "Family",
    imageUrl: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "p11",
    title: "Divorce from Justine",
    date: new Date("2008-09-13"),
    description: "Musk and Justine divorced after eight years of marriage. They share custody of their five children.",
    category: "Relationship",
    imageUrl: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "p12",
    title: "Marriage to Talulah Riley",
    date: new Date("2010-09-25"),
    description: "Musk married English actress Talulah Riley.",
    category: "Relationship",
    imageUrl: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "p13",
    title: "Divorce from Talulah Riley",
    date: new Date("2012-01-19"),
    description: "Musk and Riley divorced for the first time.",
    category: "Relationship",
    imageUrl: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "p14",
    title: "Remarriage to Talulah Riley",
    date: new Date("2013-07-01"),
    description: "Musk and Riley remarried.",
    category: "Relationship",
    imageUrl: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "p15",
    title: "Second Divorce from Talulah Riley",
    date: new Date("2016-10-01"),
    description: "Musk and Riley divorced for the second time.",
    category: "Relationship",
    imageUrl: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "p16",
    title: "Relationship with Amber Heard",
    date: new Date("2016-07-01"),
    description: "Musk began dating actress Amber Heard following her divorce from Johnny Depp.",
    category: "Relationship",
    imageUrl: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "p17",
    title: "Breakup with Amber Heard",
    date: new Date("2017-08-01"),
    description: "Musk and Heard ended their relationship after one year of dating.",
    category: "Relationship",
    imageUrl: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "p18",
    title: "Relationship with Grimes",
    date: new Date("2018-05-01"),
    description: "Musk began dating Canadian musician Grimes (Claire Boucher).",
    category: "Relationship",
    imageUrl: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "p19",
    title: "Son with Grimes",
    date: new Date("2020-05-04"),
    description:
      "Musk and Grimes had their first child together, a son named X Æ A-12 (later changed to X Æ A-Xii due to California naming laws).",
    category: "Family",
    imageUrl: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "p20",
    title: "Separation from Grimes",
    date: new Date("2021-09-24"),
    description:
      "Musk announced that he and Grimes were 'semi-separated' but still on good terms and co-parenting their son.",
    category: "Relationship",
    imageUrl: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "p21",
    title: "Daughter with Grimes",
    date: new Date("2021-12-01"),
    description: "Musk and Grimes had a daughter via surrogate named Exa Dark Sideræl Musk, nicknamed Y.",
    category: "Family",
    imageUrl: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "p22",
    title: "Twins with Shivon Zilis",
    date: new Date("2021-11-01"),
    description: "Musk had twins with Shivon Zilis, a director at Neuralink. This was revealed in July 2022.",
    category: "Family",
    imageUrl: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "p23",
    title: "Third Child with Grimes",
    date: new Date("2022-03-01"),
    description: "Musk and Grimes had a third child together, a son named Techno Mechanicus, nicknamed Tau.",
    category: "Family",
    imageUrl: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "p24",
    title: "Child Gender Change",
    date: new Date("2022-04-18"),
    description:
      "One of Musk's children with Justine Wilson filed to change her name to Vivian Jenna Wilson, citing gender identity and a desire to no longer be related to her biological father.",
    category: "Family",
    imageUrl: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "p25",
    title: "Brief Relationship with Natasha Bassett",
    date: new Date("2022-02-01"),
    description: "Musk reportedly dated Australian actress Natasha Bassett for a brief period.",
    category: "Relationship",
    imageUrl: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "p26",
    title: "Rumored Relationship with Nicole Shanahan",
    date: new Date("2023-01-15"),
    description:
      "Rumors circulated about Musk dating Nicole Shanahan, ex-wife of Google co-founder Sergey Brin. Both denied the rumors.",
    category: "Relationship",
    imageUrl: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "p27",
    title: "Third Child with Shivon Zilis",
    date: new Date("2023-09-15"),
    description: "Reports emerged of a third child born to Musk and Shivon Zilis (unconfirmed).",
    category: "Family",
    imageUrl: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "p28",
    title: "Brief Reconciliation with Grimes",
    date: new Date("2023-08-01"),
    description: "Musk and Grimes reportedly reconciled briefly to co-parent their children more closely.",
    category: "Relationship",
    imageUrl: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "p29",
    title: "Fourth Child with Grimes",
    date: new Date("2024-01-10"),
    description: "Rumors of a fourth child with Grimes named Odysseus Musk (unconfirmed).",
    category: "Family",
    imageUrl: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "p30",
    title: "Rumored Relationship with Ilona Maher",
    date: new Date("2024-03-01"),
    description:
      "Speculation about Musk dating Olympic rugby player Ilona Maher following the 2024 Paris Olympics (speculative).",
    category: "Relationship",
    imageUrl: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "p31",
    title: "Reconciliation with Shivon Zilis",
    date: new Date("2024-05-15"),
    description:
      "Reports of Musk and Shivon Zilis reconciling and focusing on their children and shared work at Neuralink (speculative).",
    category: "Relationship",
    imageUrl: "/placeholder.svg?height=200&width=300",
  },
  {
    id: "p32",
    title: "Fourth Child with Shivon Zilis",
    date: new Date("2025-03-15"),
    description:
      "Speculative birth of a fourth child with Shivon Zilis named Nova Quantum Musk (entirely fictional for analytical purposes).",
    category: "Family",
    imageUrl: "/placeholder.svg?height=200&width=300",
  },
]

